version: "4.1"
services:
    alvan-server:
        build: ./ALVAN_REST_API
        container_name: alvan_server_c
        ports:
            - '5000:5000'
        stdin_open: true
        tty: true
        volumes:
            - ./alvan-server:/app
    alvan-hub-ui:
        build: ./ALVAN_HUB_UI/alvan-hub-ui
        container_name: alvan_hub_ui_c
        ports:
            - '3000:3000'
        stdin_open: true
        tty: true
        volumes:
            - ./alvan-hub-ui:/app
            - /app/node_modules
            - /app/tests
            - /app/src