// https://developers.google.com/calendar/api/v3/reference/events#resource-representations

const mockWeatherCall = {
  location: {
    name: 'Philadelphia',
    region: 'Pennsylvania',
    country: 'United States of America',
    lat: 39.95,
    lon: -75.16,
    tz_id: 'America/New_York',
    localtime_epoch: 1655989264,
    localtime: '2022-06-23 9:01',
  },
  current: {
    last_updated_epoch: 1655988300,
    last_updated: '2022-06-23 08:45',
    temp_c: 19.4,
    temp_f: 66.9,
    is_day: 1,
    condition: {
      text: 'Overcast',
      icon: '//cdn.weatherapi.com/weather/64x64/day/122.png',
      code: 1009,
    },
    wind_mph: 9.4,
    wind_kph: 15.1,
    wind_degree: 80,
    wind_dir: 'E',
    pressure_mb: 1014,
    pressure_in: 29.93,
    precip_mm: 0.1,
    precip_in: 0,
    humidity: 84,
    cloud: 100,
    feelslike_c: 19.4,
    feelslike_f: 66.9,
    vis_km: 16,
    vis_miles: 9,
    uv: 4,
    gust_mph: 7.4,
    gust_kph: 11.9,
  },
  forecast: {
    forecastday: [
      {
        date: '2022-06-23',
        date_epoch: 1655942400,
        day: {
          maxtemp_c: 19.7,
          maxtemp_f: 67.5,
          mintemp_c: 16.3,
          mintemp_f: 61.3,
          avgtemp_c: 17.5,
          avgtemp_f: 63.5,
          maxwind_mph: 7.4,
          maxwind_kph: 11.9,
          totalprecip_mm: 31.5,
          totalprecip_in: 1.24,
          avgvis_km: 6.7,
          avgvis_miles: 4,
          avghumidity: 94,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 96,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Heavy rain',
            icon: '//cdn.weatherapi.com/weather/64x64/day/308.png',
            code: 1195,
          },
          uv: 1,
        },
        astro: {
          sunrise: '05:33 AM',
          sunset: '08:33 PM',
          moonrise: '02:11 AM',
          moonset: '03:40 PM',
          moon_phase: 'Last Quarter',
          moon_illumination: '25',
        },
        hour: [
          {
            time_epoch: 1655956800,
            time: '2022-06-23 00:00',
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 92,
            wind_dir: 'E',
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1,
          },
          {
            time_epoch: 1655960400,
            time: '2022-06-23 01:00',
            temp_c: 17.3,
            temp_f: 63.1,
            is_day: 0,
            condition: {
              text: 'Light rain shower',
              icon: '//cdn.weatherapi.com/weather/64x64/night/353.png',
              code: 1240,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 96,
            wind_dir: 'E',
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 97,
            cloud: 100,
            feelslike_c: 17.3,
            feelslike_f: 63.1,
            windchill_c: 17.3,
            windchill_f: 63.1,
            heatindex_c: 17.3,
            heatindex_f: 63.1,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 0,
            chance_of_rain: 69,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1,
          },
          {
            time_epoch: 1655964000,
            time: '2022-06-23 02:00',
            temp_c: 17.3,
            temp_f: 63.1,
            is_day: 0,
            condition: {
              text: 'Light rain shower',
              icon: '//cdn.weatherapi.com/weather/64x64/night/353.png',
              code: 1240,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 103,
            wind_dir: 'ESE',
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0.8,
            precip_in: 0.03,
            humidity: 97,
            cloud: 100,
            feelslike_c: 17.3,
            feelslike_f: 63.1,
            windchill_c: 17.3,
            windchill_f: 63.1,
            heatindex_c: 17.3,
            heatindex_f: 63.1,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.1,
            gust_kph: 16.2,
            uv: 1,
          },
          {
            time_epoch: 1655967600,
            time: '2022-06-23 03:00',
            temp_c: 17.2,
            temp_f: 63,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 105,
            wind_dir: 'ESE',
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 17.2,
            feelslike_f: 63,
            windchill_c: 17.2,
            windchill_f: 63,
            heatindex_c: 17.2,
            heatindex_f: 63,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 10.5,
            gust_kph: 16.9,
            uv: 1,
          },
          {
            time_epoch: 1655971200,
            time: '2022-06-23 04:00',
            temp_c: 17,
            temp_f: 62.6,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 103,
            wind_dir: 'ESE',
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 100,
            feelslike_c: 17,
            feelslike_f: 62.6,
            windchill_c: 17,
            windchill_f: 62.6,
            heatindex_c: 17,
            heatindex_f: 62.6,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1,
          },
          {
            time_epoch: 1655974800,
            time: '2022-06-23 05:00',
            temp_c: 16.8,
            temp_f: 62.2,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 96,
            wind_dir: 'E',
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 95,
            cloud: 100,
            feelslike_c: 16.8,
            feelslike_f: 62.2,
            windchill_c: 16.8,
            windchill_f: 62.2,
            heatindex_c: 16.8,
            heatindex_f: 62.2,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 1,
            chance_of_rain: 75,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 9.6,
            gust_kph: 15.5,
            uv: 1,
          },
          {
            time_epoch: 1655978400,
            time: '2022-06-23 06:00',
            temp_c: 16.7,
            temp_f: 62.1,
            is_day: 1,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/day/143.png',
              code: 1030,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 93,
            wind_dir: 'E',
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 16.7,
            feelslike_f: 62.1,
            windchill_c: 16.7,
            windchill_f: 62.1,
            heatindex_c: 16.7,
            heatindex_f: 62.1,
            dewpoint_c: 16,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 4,
          },
          {
            time_epoch: 1655982000,
            time: '2022-06-23 07:00',
            temp_c: 16.7,
            temp_f: 62.1,
            is_day: 1,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/day/143.png',
              code: 1030,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 95,
            wind_dir: 'E',
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 96,
            cloud: 100,
            feelslike_c: 16.7,
            feelslike_f: 62.1,
            windchill_c: 16.7,
            windchill_f: 62.1,
            heatindex_c: 16.7,
            heatindex_f: 62.1,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 1,
            chance_of_rain: 76,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 4,
          },
          {
            time_epoch: 1655985600,
            time: '2022-06-23 08:00',
            temp_c: 16.7,
            temp_f: 62.1,
            is_day: 1,
            condition: {
              text: 'Light rain',
              icon: '//cdn.weatherapi.com/weather/64x64/day/296.png',
              code: 1183,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 85,
            wind_dir: 'E',
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0.9,
            precip_in: 0.04,
            humidity: 96,
            cloud: 100,
            feelslike_c: 16.7,
            feelslike_f: 62.1,
            windchill_c: 16.7,
            windchill_f: 62.1,
            heatindex_c: 16.7,
            heatindex_f: 62.1,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 1,
            chance_of_rain: 96,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 4,
          },
          {
            time_epoch: 1655989200,
            time: '2022-06-23 09:00',
            temp_c: 16.9,
            temp_f: 62.4,
            is_day: 1,
            condition: {
              text: 'Light rain',
              icon: '//cdn.weatherapi.com/weather/64x64/day/296.png',
              code: 1183,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 72,
            wind_dir: 'ENE',
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 1,
            precip_in: 0.04,
            humidity: 95,
            cloud: 100,
            feelslike_c: 16.9,
            feelslike_f: 62.4,
            windchill_c: 16.9,
            windchill_f: 62.4,
            heatindex_c: 16.9,
            heatindex_f: 62.4,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 1,
            chance_of_rain: 96,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 4,
          },
          {
            time_epoch: 1655992800,
            time: '2022-06-23 10:00',
            temp_c: 17.1,
            temp_f: 62.8,
            is_day: 1,
            condition: {
              text: 'Light rain',
              icon: '//cdn.weatherapi.com/weather/64x64/day/296.png',
              code: 1183,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 24,
            wind_dir: 'NNE',
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 1.6,
            precip_in: 0.06,
            humidity: 96,
            cloud: 100,
            feelslike_c: 17.1,
            feelslike_f: 62.8,
            windchill_c: 17.1,
            windchill_f: 62.8,
            heatindex_c: 17.1,
            heatindex_f: 62.8,
            dewpoint_c: 16.4,
            dewpoint_f: 61.5,
            will_it_rain: 1,
            chance_of_rain: 95,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 6,
            gust_kph: 9.7,
            uv: 4,
          },
          {
            time_epoch: 1655996400,
            time: '2022-06-23 11:00',
            temp_c: 17.2,
            temp_f: 63,
            is_day: 1,
            condition: {
              text: 'Moderate rain',
              icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
              code: 1189,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 62,
            wind_dir: 'ENE',
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 6.8,
            precip_in: 0.27,
            humidity: 98,
            cloud: 100,
            feelslike_c: 17.2,
            feelslike_f: 63,
            windchill_c: 17.2,
            windchill_f: 63,
            heatindex_c: 17.2,
            heatindex_f: 63,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 1,
            chance_of_rain: 95,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 4,
          },
          {
            time_epoch: 1656000000,
            time: '2022-06-23 12:00',
            temp_c: 17.6,
            temp_f: 63.7,
            is_day: 1,
            condition: {
              text: 'Moderate rain',
              icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
              code: 1189,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 359,
            wind_dir: 'N',
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 2.6,
            precip_in: 0.1,
            humidity: 96,
            cloud: 100,
            feelslike_c: 17.6,
            feelslike_f: 63.7,
            windchill_c: 17.6,
            windchill_f: 63.7,
            heatindex_c: 17.6,
            heatindex_f: 63.7,
            dewpoint_c: 17,
            dewpoint_f: 62.6,
            will_it_rain: 1,
            chance_of_rain: 95,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 4,
          },
          {
            time_epoch: 1656003600,
            time: '2022-06-23 13:00',
            temp_c: 17.6,
            temp_f: 63.7,
            is_day: 1,
            condition: {
              text: 'Moderate rain',
              icon: '//cdn.weatherapi.com/weather/64x64/day/302.png',
              code: 1189,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 47,
            wind_dir: 'NE',
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 2.8,
            precip_in: 0.11,
            humidity: 97,
            cloud: 81,
            feelslike_c: 17.6,
            feelslike_f: 63.7,
            windchill_c: 17.6,
            windchill_f: 63.7,
            heatindex_c: 17.6,
            heatindex_f: 63.7,
            dewpoint_c: 17.1,
            dewpoint_f: 62.8,
            will_it_rain: 1,
            chance_of_rain: 94,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 4,
          },
          {
            time_epoch: 1656007200,
            time: '2022-06-23 14:00',
            temp_c: 18.3,
            temp_f: 64.9,
            is_day: 1,
            condition: {
              text: 'Heavy rain at times',
              icon: '//cdn.weatherapi.com/weather/64x64/day/305.png',
              code: 1192,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 18,
            wind_dir: 'NNE',
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 14.4,
            precip_in: 0.57,
            humidity: 94,
            cloud: 64,
            feelslike_c: 18.3,
            feelslike_f: 64.9,
            windchill_c: 18.3,
            windchill_f: 64.9,
            heatindex_c: 18.3,
            heatindex_f: 64.9,
            dewpoint_c: 17.4,
            dewpoint_f: 63.3,
            will_it_rain: 1,
            chance_of_rain: 94,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6,
            vis_miles: 3,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 4,
          },
          {
            time_epoch: 1656010800,
            time: '2022-06-23 15:00',
            temp_c: 18.1,
            temp_f: 64.6,
            is_day: 1,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/day/143.png',
              code: 1030,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 352,
            wind_dir: 'N',
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 50,
            feelslike_c: 18.1,
            feelslike_f: 64.6,
            windchill_c: 18.1,
            windchill_f: 64.6,
            heatindex_c: 18.1,
            heatindex_f: 64.6,
            dewpoint_c: 17.4,
            dewpoint_f: 63.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6,
            gust_kph: 9.7,
            uv: 4,
          },
          {
            time_epoch: 1656014400,
            time: '2022-06-23 16:00',
            temp_c: 18,
            temp_f: 64.4,
            is_day: 1,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/day/143.png',
              code: 1030,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 4,
            wind_dir: 'N',
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 100,
            feelslike_c: 18,
            feelslike_f: 64.4,
            windchill_c: 18,
            windchill_f: 64.4,
            heatindex_c: 18,
            heatindex_f: 64.4,
            dewpoint_c: 17.2,
            dewpoint_f: 63,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 4,
          },
          {
            time_epoch: 1656018000,
            time: '2022-06-23 17:00',
            temp_c: 18.7,
            temp_f: 65.7,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 1,
            wind_dir: 'N',
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 91,
            cloud: 65,
            feelslike_c: 18.7,
            feelslike_f: 65.7,
            windchill_c: 18.7,
            windchill_f: 65.7,
            heatindex_c: 18.7,
            heatindex_f: 65.7,
            dewpoint_c: 17.1,
            dewpoint_f: 62.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 4,
          },
          {
            time_epoch: 1656021600,
            time: '2022-06-23 18:00',
            temp_c: 19.7,
            temp_f: 67.5,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 359,
            wind_dir: 'N',
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 30,
            feelslike_c: 19.7,
            feelslike_f: 67.5,
            windchill_c: 19.7,
            windchill_f: 67.5,
            heatindex_c: 19.7,
            heatindex_f: 67.5,
            dewpoint_c: 17.1,
            dewpoint_f: 62.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 5,
          },
          {
            time_epoch: 1656025200,
            time: '2022-06-23 19:00',
            temp_c: 19.7,
            temp_f: 67.5,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 9,
            wind_dir: 'N',
            pressure_mb: 1014,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 32,
            feelslike_c: 19.7,
            feelslike_f: 67.5,
            windchill_c: 19.7,
            windchill_f: 67.5,
            heatindex_c: 19.7,
            heatindex_f: 67.5,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 5,
          },
          {
            time_epoch: 1656028800,
            time: '2022-06-23 20:00',
            temp_c: 18.1,
            temp_f: 64.6,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 6,
            wind_dir: 'N',
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 45,
            feelslike_c: 18.1,
            feelslike_f: 64.6,
            windchill_c: 18.1,
            windchill_f: 64.6,
            heatindex_c: 18.1,
            heatindex_f: 64.6,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 5,
          },
          {
            time_epoch: 1656032400,
            time: '2022-06-23 21:00',
            temp_c: 16.9,
            temp_f: 62.4,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 8,
            wind_dir: 'N',
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 31,
            feelslike_c: 16.9,
            feelslike_f: 62.4,
            windchill_c: 16.9,
            windchill_f: 62.4,
            heatindex_c: 16.9,
            heatindex_f: 62.4,
            dewpoint_c: 15.3,
            dewpoint_f: 59.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1,
          },
          {
            time_epoch: 1656036000,
            time: '2022-06-23 22:00',
            temp_c: 16.5,
            temp_f: 61.7,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 11,
            wind_dir: 'NNE',
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 18,
            feelslike_c: 16.5,
            feelslike_f: 61.7,
            windchill_c: 16.5,
            windchill_f: 61.7,
            heatindex_c: 16.5,
            heatindex_f: 61.7,
            dewpoint_c: 14.9,
            dewpoint_f: 58.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.1,
            gust_kph: 13,
            uv: 1,
          },
          {
            time_epoch: 1656039600,
            time: '2022-06-23 23:00',
            temp_c: 16.3,
            temp_f: 61.3,
            is_day: 0,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 19,
            wind_dir: 'NNE',
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 92,
            cloud: 28,
            feelslike_c: 16.3,
            feelslike_f: 61.3,
            windchill_c: 16.3,
            windchill_f: 61.3,
            heatindex_c: 16.3,
            heatindex_f: 61.3,
            dewpoint_c: 14.9,
            dewpoint_f: 58.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.9,
            gust_kph: 11.2,
            uv: 1,
          },
        ],
      },
      {
        date: '2022-06-24',
        date_epoch: 1656028800,
        day: {
          maxtemp_c: 28.7,
          maxtemp_f: 83.7,
          mintemp_c: 14.8,
          mintemp_f: 58.6,
          avgtemp_c: 21.5,
          avgtemp_f: 70.6,
          maxwind_mph: 7.8,
          maxwind_kph: 12.6,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          avgvis_km: 8,
          avgvis_miles: 4,
          avghumidity: 71,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Partly cloudy',
            icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
            code: 1003,
          },
          uv: 9,
        },
        astro: {
          sunrise: '05:33 AM',
          sunset: '08:33 PM',
          moonrise: '02:35 AM',
          moonset: '04:42 PM',
          moon_phase: 'Waning Crescent',
          moon_illumination: '18',
        },
        hour: [
          {
            time_epoch: 1656043200,
            time: '2022-06-24 00:00',
            temp_c: 15.8,
            temp_f: 60.4,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 13,
            wind_dir: 'NNE',
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 93,
            cloud: 14,
            feelslike_c: 15.8,
            feelslike_f: 60.4,
            windchill_c: 15.8,
            windchill_f: 60.4,
            heatindex_c: 15.8,
            heatindex_f: 60.4,
            dewpoint_c: 14.7,
            dewpoint_f: 58.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1,
          },
          {
            time_epoch: 1656046800,
            time: '2022-06-24 01:00',
            temp_c: 15.5,
            temp_f: 59.9,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 11,
            wind_dir: 'NNE',
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            humidity: 94,
            cloud: 18,
            feelslike_c: 15.5,
            feelslike_f: 59.9,
            windchill_c: 15.5,
            windchill_f: 59.9,
            heatindex_c: 15.5,
            heatindex_f: 59.9,
            dewpoint_c: 14.6,
            dewpoint_f: 58.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1,
          },
          {
            time_epoch: 1656050400,
            time: '2022-06-24 02:00',
            temp_c: 15.4,
            temp_f: 59.7,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 10,
            wind_dir: 'N',
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0,
            precip_in: 0,
            humidity: 94,
            cloud: 18,
            feelslike_c: 15.4,
            feelslike_f: 59.7,
            windchill_c: 15.4,
            windchill_f: 59.7,
            heatindex_c: 15.4,
            heatindex_f: 59.7,
            dewpoint_c: 14.5,
            dewpoint_f: 58.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1,
          },
          {
            time_epoch: 1656054000,
            time: '2022-06-24 03:00',
            temp_c: 15.2,
            temp_f: 59.4,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 4,
            wind_dir: 'N',
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 21,
            feelslike_c: 15.2,
            feelslike_f: 59.4,
            windchill_c: 15.2,
            windchill_f: 59.4,
            heatindex_c: 15.2,
            heatindex_f: 59.4,
            dewpoint_c: 14.3,
            dewpoint_f: 57.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 1,
          },
          {
            time_epoch: 1656057600,
            time: '2022-06-24 04:00',
            temp_c: 15,
            temp_f: 59,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 359,
            wind_dir: 'N',
            pressure_mb: 1017,
            pressure_in: 30.02,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 23,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 15,
            heatindex_f: 59,
            dewpoint_c: 14.2,
            dewpoint_f: 57.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1,
          },
          {
            time_epoch: 1656061200,
            time: '2022-06-24 05:00',
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 0,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
              code: 1030,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 9,
            wind_dir: 'N',
            pressure_mb: 1017,
            pressure_in: 30.02,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 27,
            feelslike_c: 15,
            feelslike_f: 59,
            windchill_c: 15,
            windchill_f: 59,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            dewpoint_c: 14.1,
            dewpoint_f: 57.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 1,
          },
          {
            time_epoch: 1656064800,
            time: '2022-06-24 06:00',
            temp_c: 14.9,
            temp_f: 58.8,
            is_day: 1,
            condition: {
              text: 'Mist',
              icon: '//cdn.weatherapi.com/weather/64x64/day/143.png',
              code: 1030,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 10,
            wind_dir: 'N',
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 32,
            feelslike_c: 15.2,
            feelslike_f: 59.4,
            windchill_c: 15.2,
            windchill_f: 59.4,
            heatindex_c: 14.9,
            heatindex_f: 58.8,
            dewpoint_c: 14.2,
            dewpoint_f: 57.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 3,
          },
          {
            time_epoch: 1656068400,
            time: '2022-06-24 07:00',
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 2,
            wind_dir: 'N',
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 32,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: 14.7,
            dewpoint_f: 58.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 5,
          },
          {
            time_epoch: 1656072000,
            time: '2022-06-24 08:00',
            temp_c: 18.4,
            temp_f: 65.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 16,
            wind_dir: 'NNE',
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 82,
            cloud: 17,
            feelslike_c: 18.4,
            feelslike_f: 65.1,
            windchill_c: 18.4,
            windchill_f: 65.1,
            heatindex_c: 18.4,
            heatindex_f: 65.1,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 5,
          },
          {
            time_epoch: 1656075600,
            time: '2022-06-24 09:00',
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 23,
            wind_dir: 'NNE',
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 72,
            cloud: 28,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: 15.3,
            dewpoint_f: 59.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 6,
          },
          {
            time_epoch: 1656079200,
            time: '2022-06-24 10:00',
            temp_c: 22.4,
            temp_f: 72.3,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 6,
            wind_dir: 'N',
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 63,
            cloud: 26,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.4,
            windchill_f: 72.3,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 15.1,
            dewpoint_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.8,
            gust_kph: 6.1,
            uv: 6,
          },
          {
            time_epoch: 1656082800,
            time: '2022-06-24 11:00',
            temp_c: 24.7,
            temp_f: 76.5,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 356,
            wind_dir: 'N',
            pressure_mb: 1018,
            pressure_in: 30.05,
            precip_mm: 0,
            precip_in: 0,
            humidity: 57,
            cloud: 22,
            feelslike_c: 25.9,
            feelslike_f: 78.6,
            windchill_c: 24.7,
            windchill_f: 76.5,
            heatindex_c: 25.9,
            heatindex_f: 78.6,
            dewpoint_c: 15.5,
            dewpoint_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 6,
          },
          {
            time_epoch: 1656086400,
            time: '2022-06-24 12:00',
            temp_c: 28.7,
            temp_f: 83.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 355,
            wind_dir: 'N',
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0,
            precip_in: 0,
            humidity: 51,
            cloud: 12,
            feelslike_c: 29.7,
            feelslike_f: 85.5,
            windchill_c: 28.7,
            windchill_f: 83.7,
            heatindex_c: 29.7,
            heatindex_f: 85.5,
            dewpoint_c: 17.6,
            dewpoint_f: 63.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 7,
          },
          {
            time_epoch: 1656090000,
            time: '2022-06-24 13:00',
            temp_c: 28.5,
            temp_f: 83.3,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 350,
            wind_dir: 'N',
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0,
            precip_in: 0,
            humidity: 47,
            cloud: 17,
            feelslike_c: 29.1,
            feelslike_f: 84.4,
            windchill_c: 28.5,
            windchill_f: 83.3,
            heatindex_c: 29.1,
            heatindex_f: 84.4,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 7,
          },
          {
            time_epoch: 1656093600,
            time: '2022-06-24 14:00',
            temp_c: 28.5,
            temp_f: 83.3,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 344,
            wind_dir: 'NNW',
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 44,
            cloud: 40,
            feelslike_c: 28.8,
            feelslike_f: 83.8,
            windchill_c: 28.5,
            windchill_f: 83.3,
            heatindex_c: 28.8,
            heatindex_f: 83.8,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 7,
          },
          {
            time_epoch: 1656097200,
            time: '2022-06-24 15:00',
            temp_c: 28.7,
            temp_f: 83.7,
            is_day: 1,
            condition: {
              text: 'Cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
              code: 1006,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 337,
            wind_dir: 'NNW',
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 42,
            cloud: 69,
            feelslike_c: 28.8,
            feelslike_f: 83.8,
            windchill_c: 28.7,
            windchill_f: 83.7,
            heatindex_c: 28.8,
            heatindex_f: 83.8,
            dewpoint_c: 14.6,
            dewpoint_f: 58.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 6,
          },
          {
            time_epoch: 1656100800,
            time: '2022-06-24 16:00',
            temp_c: 28.7,
            temp_f: 83.7,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 334,
            wind_dir: 'NNW',
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 42,
            cloud: 50,
            feelslike_c: 28.8,
            feelslike_f: 83.8,
            windchill_c: 28.7,
            windchill_f: 83.7,
            heatindex_c: 28.8,
            heatindex_f: 83.8,
            dewpoint_c: 14.6,
            dewpoint_f: 58.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.5,
            gust_kph: 4,
            uv: 7,
          },
          {
            time_epoch: 1656104400,
            time: '2022-06-24 17:00',
            temp_c: 27.6,
            temp_f: 81.7,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 145,
            wind_dir: 'SE',
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 47,
            cloud: 44,
            feelslike_c: 28,
            feelslike_f: 82.4,
            windchill_c: 27.6,
            windchill_f: 81.7,
            heatindex_c: 28,
            heatindex_f: 82.4,
            dewpoint_c: 15.1,
            dewpoint_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 7,
          },
          {
            time_epoch: 1656108000,
            time: '2022-06-24 18:00',
            temp_c: 25.6,
            temp_f: 78.1,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 155,
            wind_dir: 'SSE',
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0,
            precip_in: 0,
            humidity: 55,
            cloud: 45,
            feelslike_c: 26.6,
            feelslike_f: 79.9,
            windchill_c: 25.6,
            windchill_f: 78.1,
            heatindex_c: 26.6,
            heatindex_f: 79.9,
            dewpoint_c: 16,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 7,
          },
          {
            time_epoch: 1656111600,
            time: '2022-06-24 19:00',
            temp_c: 24.6,
            temp_f: 76.3,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 158,
            wind_dir: 'SSE',
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 62,
            cloud: 46,
            feelslike_c: 25.9,
            feelslike_f: 78.6,
            windchill_c: 24.6,
            windchill_f: 76.3,
            heatindex_c: 25.9,
            heatindex_f: 78.6,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.6,
            gust_kph: 15.5,
            uv: 6,
          },
          {
            time_epoch: 1656115200,
            time: '2022-06-24 20:00',
            temp_c: 23.1,
            temp_f: 73.6,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 167,
            wind_dir: 'SSE',
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            humidity: 67,
            cloud: 30,
            feelslike_c: 25,
            feelslike_f: 77,
            windchill_c: 23.1,
            windchill_f: 73.6,
            heatindex_c: 25,
            heatindex_f: 77,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 6,
          },
          {
            time_epoch: 1656118800,
            time: '2022-06-24 21:00',
            temp_c: 21.7,
            temp_f: 71.1,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 175,
            wind_dir: 'S',
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            humidity: 73,
            cloud: 22,
            feelslike_c: 21.7,
            feelslike_f: 71.1,
            windchill_c: 21.7,
            windchill_f: 71.1,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 16.5,
            dewpoint_f: 61.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1,
          },
          {
            time_epoch: 1656122400,
            time: '2022-06-24 22:00',
            temp_c: 20.6,
            temp_f: 69.1,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 175,
            wind_dir: 'S',
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 77,
            cloud: 15,
            feelslike_c: 20.6,
            feelslike_f: 69.1,
            windchill_c: 20.6,
            windchill_f: 69.1,
            heatindex_c: 20.6,
            heatindex_f: 69.1,
            dewpoint_c: 16.4,
            dewpoint_f: 61.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.5,
            gust_kph: 13.7,
            uv: 1,
          },
          {
            time_epoch: 1656126000,
            time: '2022-06-24 23:00',
            temp_c: 19.8,
            temp_f: 67.6,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 178,
            wind_dir: 'S',
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 80,
            cloud: 10,
            feelslike_c: 19.8,
            feelslike_f: 67.6,
            windchill_c: 19.8,
            windchill_f: 67.6,
            heatindex_c: 19.8,
            heatindex_f: 67.6,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 1,
          },
        ],
      },
      {
        date: '2022-06-25',
        date_epoch: 1656115200,
        day: {
          maxtemp_c: 31.8,
          maxtemp_f: 89.2,
          mintemp_c: 17.7,
          mintemp_f: 63.9,
          avgtemp_c: 24.6,
          avgtemp_f: 76.3,
          maxwind_mph: 8.3,
          maxwind_kph: 13.3,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 64,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: 'Sunny',
            icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
            code: 1000,
          },
          uv: 9,
        },
        astro: {
          sunrise: '05:33 AM',
          sunset: '08:33 PM',
          moonrise: '03:02 AM',
          moonset: '05:45 PM',
          moon_phase: 'Waning Crescent',
          moon_illumination: '10',
        },
        hour: [
          {
            time_epoch: 1656129600,
            time: '2022-06-25 00:00',
            temp_c: 19,
            temp_f: 66.2,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 200,
            wind_dir: 'SSW',
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 81,
            cloud: 9,
            feelslike_c: 19,
            feelslike_f: 66.2,
            windchill_c: 19,
            windchill_f: 66.2,
            heatindex_c: 19,
            heatindex_f: 66.2,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 1,
          },
          {
            time_epoch: 1656133200,
            time: '2022-06-25 01:00',
            temp_c: 18.6,
            temp_f: 65.5,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 208,
            wind_dir: 'SSW',
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 11,
            feelslike_c: 18.6,
            feelslike_f: 65.5,
            windchill_c: 18.6,
            windchill_f: 65.5,
            heatindex_c: 18.6,
            heatindex_f: 65.5,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1,
          },
          {
            time_epoch: 1656136800,
            time: '2022-06-25 02:00',
            temp_c: 18.2,
            temp_f: 64.8,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 211,
            wind_dir: 'SSW',
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 18,
            feelslike_c: 18.2,
            feelslike_f: 64.8,
            windchill_c: 18.2,
            windchill_f: 64.8,
            heatindex_c: 18.2,
            heatindex_f: 64.8,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 1,
          },
          {
            time_epoch: 1656140400,
            time: '2022-06-25 03:00',
            temp_c: 18,
            temp_f: 64.4,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 205,
            wind_dir: 'SSW',
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            humidity: 87,
            cloud: 11,
            feelslike_c: 18,
            feelslike_f: 64.4,
            windchill_c: 18,
            windchill_f: 64.4,
            heatindex_c: 18,
            heatindex_f: 64.4,
            dewpoint_c: 15.8,
            dewpoint_f: 60.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 1,
          },
          {
            time_epoch: 1656144000,
            time: '2022-06-25 04:00',
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 216,
            wind_dir: 'SW',
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 12,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 16,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 1,
          },
          {
            time_epoch: 1656147600,
            time: '2022-06-25 05:00',
            temp_c: 17.7,
            temp_f: 63.9,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 230,
            wind_dir: 'SW',
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 14,
            feelslike_c: 17.7,
            feelslike_f: 63.9,
            windchill_c: 17.7,
            windchill_f: 63.9,
            heatindex_c: 17.7,
            heatindex_f: 63.9,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1,
          },
          {
            time_epoch: 1656151200,
            time: '2022-06-25 06:00',
            temp_c: 17.8,
            temp_f: 64,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 240,
            wind_dir: 'WSW',
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            humidity: 90,
            cloud: 17,
            feelslike_c: 17.8,
            feelslike_f: 64,
            windchill_c: 17.8,
            windchill_f: 64,
            heatindex_c: 17.8,
            heatindex_f: 64,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 5,
          },
          {
            time_epoch: 1656154800,
            time: '2022-06-25 07:00',
            temp_c: 19.3,
            temp_f: 66.7,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 251,
            wind_dir: 'WSW',
            pressure_mb: 1021,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            humidity: 85,
            cloud: 37,
            feelslike_c: 19.3,
            feelslike_f: 66.7,
            windchill_c: 19.3,
            windchill_f: 66.7,
            heatindex_c: 19.3,
            heatindex_f: 66.7,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
            uv: 5,
          },
          {
            time_epoch: 1656158400,
            time: '2022-06-25 08:00',
            temp_c: 21.3,
            temp_f: 70.3,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 254,
            wind_dir: 'WSW',
            pressure_mb: 1022,
            pressure_in: 30.17,
            precip_mm: 0,
            precip_in: 0,
            humidity: 78,
            cloud: 23,
            feelslike_c: 21.3,
            feelslike_f: 70.3,
            windchill_c: 21.3,
            windchill_f: 70.3,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 17.4,
            dewpoint_f: 63.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 6,
          },
          {
            time_epoch: 1656162000,
            time: '2022-06-25 09:00',
            temp_c: 23.5,
            temp_f: 74.3,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 251,
            wind_dir: 'WSW',
            pressure_mb: 1022,
            pressure_in: 30.17,
            precip_mm: 0,
            precip_in: 0,
            humidity: 69,
            cloud: 14,
            feelslike_c: 25.3,
            feelslike_f: 77.5,
            windchill_c: 23.5,
            windchill_f: 74.3,
            heatindex_c: 25.3,
            heatindex_f: 77.5,
            dewpoint_c: 17.6,
            dewpoint_f: 63.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 6,
          },
          {
            time_epoch: 1656165600,
            time: '2022-06-25 10:00',
            temp_c: 25.6,
            temp_f: 78.1,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 248,
            wind_dir: 'WSW',
            pressure_mb: 1022,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            humidity: 60,
            cloud: 13,
            feelslike_c: 26.8,
            feelslike_f: 80.2,
            windchill_c: 25.6,
            windchill_f: 78.1,
            heatindex_c: 26.8,
            heatindex_f: 80.2,
            dewpoint_c: 17.3,
            dewpoint_f: 63.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 7,
          },
          {
            time_epoch: 1656169200,
            time: '2022-06-25 11:00',
            temp_c: 30.4,
            temp_f: 86.7,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 247,
            wind_dir: 'WSW',
            pressure_mb: 1022,
            pressure_in: 30.17,
            precip_mm: 0,
            precip_in: 0,
            humidity: 52,
            cloud: 13,
            feelslike_c: 32.4,
            feelslike_f: 90.3,
            windchill_c: 30.4,
            windchill_f: 86.7,
            heatindex_c: 32.4,
            heatindex_f: 90.3,
            dewpoint_c: 19.4,
            dewpoint_f: 66.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 8,
          },
          {
            time_epoch: 1656172800,
            time: '2022-06-25 12:00',
            temp_c: 31.8,
            temp_f: 89.2,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 245,
            wind_dir: 'WSW',
            pressure_mb: 1021,
            pressure_in: 30.16,
            precip_mm: 0,
            precip_in: 0,
            humidity: 45,
            cloud: 13,
            feelslike_c: 33.6,
            feelslike_f: 92.5,
            windchill_c: 31.8,
            windchill_f: 89.2,
            heatindex_c: 33.6,
            heatindex_f: 92.5,
            dewpoint_c: 18.5,
            dewpoint_f: 65.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.4,
            gust_kph: 8.6,
            uv: 8,
          },
          {
            time_epoch: 1656176400,
            time: '2022-06-25 13:00',
            temp_c: 31.3,
            temp_f: 88.3,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 234,
            wind_dir: 'SW',
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            humidity: 41,
            cloud: 17,
            feelslike_c: 32.1,
            feelslike_f: 89.8,
            windchill_c: 31.3,
            windchill_f: 88.3,
            heatindex_c: 32.1,
            heatindex_f: 89.8,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 8,
          },
          {
            time_epoch: 1656180000,
            time: '2022-06-25 14:00',
            temp_c: 31.5,
            temp_f: 88.7,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 234,
            wind_dir: 'SW',
            pressure_mb: 1020,
            pressure_in: 30.13,
            precip_mm: 0,
            precip_in: 0,
            humidity: 39,
            cloud: 30,
            feelslike_c: 32,
            feelslike_f: 89.6,
            windchill_c: 31.5,
            windchill_f: 88.7,
            heatindex_c: 32,
            heatindex_f: 89.6,
            dewpoint_c: 15.8,
            dewpoint_f: 60.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 8,
          },
          {
            time_epoch: 1656183600,
            time: '2022-06-25 15:00',
            temp_c: 31.7,
            temp_f: 89.1,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 248,
            wind_dir: 'WSW',
            pressure_mb: 1020,
            pressure_in: 30.12,
            precip_mm: 0,
            precip_in: 0,
            humidity: 37,
            cloud: 35,
            feelslike_c: 32,
            feelslike_f: 89.6,
            windchill_c: 31.7,
            windchill_f: 89.1,
            heatindex_c: 32,
            heatindex_f: 89.6,
            dewpoint_c: 15.4,
            dewpoint_f: 59.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 8,
          },
          {
            time_epoch: 1656187200,
            time: '2022-06-25 16:00',
            temp_c: 31.7,
            temp_f: 89.1,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 254,
            wind_dir: 'WSW',
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 37,
            cloud: 29,
            feelslike_c: 31.9,
            feelslike_f: 89.4,
            windchill_c: 31.7,
            windchill_f: 89.1,
            heatindex_c: 31.9,
            heatindex_f: 89.4,
            dewpoint_c: 15.1,
            dewpoint_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.2,
            gust_kph: 11.5,
            uv: 8,
          },
          {
            time_epoch: 1656190800,
            time: '2022-06-25 17:00',
            temp_c: 31.3,
            temp_f: 88.3,
            is_day: 1,
            condition: {
              text: 'Partly cloudy',
              icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
              code: 1003,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 261,
            wind_dir: 'W',
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 38,
            cloud: 32,
            feelslike_c: 31.6,
            feelslike_f: 88.9,
            windchill_c: 31.3,
            windchill_f: 88.3,
            heatindex_c: 31.6,
            heatindex_f: 88.9,
            dewpoint_c: 15.3,
            dewpoint_f: 59.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 8,
          },
          {
            time_epoch: 1656194400,
            time: '2022-06-25 18:00',
            temp_c: 30.2,
            temp_f: 86.4,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 248,
            wind_dir: 'WSW',
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 42,
            cloud: 22,
            feelslike_c: 30.7,
            feelslike_f: 87.3,
            windchill_c: 30.2,
            windchill_f: 86.4,
            heatindex_c: 30.7,
            heatindex_f: 87.3,
            dewpoint_c: 16,
            dewpoint_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 8,
          },
          {
            time_epoch: 1656198000,
            time: '2022-06-25 19:00',
            temp_c: 29.2,
            temp_f: 84.6,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 235,
            wind_dir: 'SW',
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0,
            precip_in: 0,
            humidity: 50,
            cloud: 12,
            feelslike_c: 30.3,
            feelslike_f: 86.5,
            windchill_c: 29.2,
            windchill_f: 84.6,
            heatindex_c: 30.3,
            heatindex_f: 86.5,
            dewpoint_c: 17.8,
            dewpoint_f: 64,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 7,
          },
          {
            time_epoch: 1656201600,
            time: '2022-06-25 20:00',
            temp_c: 26,
            temp_f: 78.8,
            is_day: 1,
            condition: {
              text: 'Sunny',
              icon: '//cdn.weatherapi.com/weather/64x64/day/113.png',
              code: 1000,
            },
            wind_mph: 7.6,
            wind_kph: 12.2,
            wind_degree: 221,
            wind_dir: 'SW',
            pressure_mb: 1020,
            pressure_in: 30.11,
            precip_mm: 0,
            precip_in: 0,
            humidity: 60,
            cloud: 12,
            feelslike_c: 27.1,
            feelslike_f: 80.8,
            windchill_c: 26,
            windchill_f: 78.8,
            heatindex_c: 27.1,
            heatindex_f: 80.8,
            dewpoint_c: 17.5,
            dewpoint_f: 63.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11.9,
            gust_kph: 19.1,
            uv: 7,
          },
          {
            time_epoch: 1656205200,
            time: '2022-06-25 21:00',
            temp_c: 24,
            temp_f: 75.2,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 204,
            wind_dir: 'SSW',
            pressure_mb: 1020,
            pressure_in: 30.12,
            precip_mm: 0,
            precip_in: 0,
            humidity: 65,
            cloud: 10,
            feelslike_c: 25.6,
            feelslike_f: 78.1,
            windchill_c: 24,
            windchill_f: 75.2,
            heatindex_c: 25.6,
            heatindex_f: 78.1,
            dewpoint_c: 17.1,
            dewpoint_f: 62.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 11,
            gust_kph: 17.6,
            uv: 1,
          },
          {
            time_epoch: 1656208800,
            time: '2022-06-25 22:00',
            temp_c: 22.8,
            temp_f: 73,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 6,
            wind_kph: 9.7,
            wind_degree: 199,
            wind_dir: 'SSW',
            pressure_mb: 1021,
            pressure_in: 30.14,
            precip_mm: 0,
            precip_in: 0,
            humidity: 68,
            cloud: 9,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 22.8,
            windchill_f: 73,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: 16.5,
            dewpoint_f: 61.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.8,
            gust_kph: 15.8,
            uv: 1,
          },
          {
            time_epoch: 1656212400,
            time: '2022-06-25 23:00',
            temp_c: 22.2,
            temp_f: 72,
            is_day: 0,
            condition: {
              text: 'Clear',
              icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 196,
            wind_dir: 'SSW',
            pressure_mb: 1021,
            pressure_in: 30.15,
            precip_mm: 0,
            precip_in: 0,
            humidity: 71,
            cloud: 10,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.2,
            windchill_f: 72,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 1,
          },
        ],
      },
    ],
  },
};

export default mockWeatherCall;
